use std::{collections::VecDeque,env,fs::{File,OpenOptions},io::{Read,Seek,SeekFrom,Write},os::unix::{fs::OpenOptionsExt,io::AsRawFd},time::{Duration,Instant}};
#[repr(C)] struct Timespec { sec:i64,nsec:i64 }
unsafe extern "C" {fn clock_gettime(id:i32,t:*mut Timespec)->i32;}
fn clock(id:i32)->u64 {let mut t=Timespec{sec:0,nsec:0}; assert_eq!(unsafe{clock_gettime(id,&mut t)},0);t.sec as u64*1_000_000_000+t.nsec as u64}
fn read(file:&mut File,b:&mut [u8])->usize {file.seek(SeekFrom::Start(0)).unwrap();file.read(b).unwrap()}
struct Target {tid:u32,start:u64,stat:File,sched:File,wchan:File}
#[derive(Clone,Copy)] struct Sample {state:u8,minor:u64,major:u64,cpu:u64,runqueue:u64,slices:u64,wchan:[u8;64]}
struct Row {before:u64,after:u64,threads:[Sample;2],status:[[u64;16];2]}
impl Target {fn sample(&mut self,full:bool)->Sample {let mut b=[0u8;4096];let mut s=Sample{state:b'?',minor:0,major:0,cpu:0,runqueue:0,slices:0,wchan:[0;64]};if full {let n=read(&mut self.stat,&mut b);let text=std::str::from_utf8(&b[..n]).unwrap();let mut f=text.rsplit_once(')').unwrap().1.split_whitespace();let mut start=0;for i in 0..20 {let v=f.next().unwrap();match i {0=>s.state=v.as_bytes()[0],7=>s.minor=v.parse().unwrap(),9=>s.major=v.parse().unwrap(),19=>start=v.parse().unwrap(),_=>()}}assert_eq!(start,self.start);read(&mut self.wchan,&mut s.wchan);}let n=read(&mut self.sched,&mut b);let mut f=std::str::from_utf8(&b[..n]).unwrap().split_whitespace();s.cpu=f.next().unwrap().parse().unwrap();s.runqueue=f.next().unwrap().parse().unwrap();s.slices=f.next().unwrap().parse().unwrap();s}}
unsafe extern "C" {fn mmap(p:*mut std::ffi::c_void,n:usize,prot:i32,flags:i32,fd:i32,off:i64)->*mut std::ffi::c_void;fn munmap(p:*mut std::ffi::c_void,n:usize)->i32;}
struct Status {p:*mut u8,_file:File}
impl Status {fn open(path:&str)->Self {let mut file=OpenOptions::new().read(true).custom_flags(0x20000).open(path).unwrap();assert_eq!(file.metadata().unwrap().len(),1024);let mut header=[0;64];file.read_exact(&mut header).unwrap();assert_eq!(&header[..4],b"LVFS");assert_eq!(u32::from_le_bytes(header[4..8].try_into().unwrap()),2);let p=unsafe{mmap(std::ptr::null_mut(),1024,1,1,file.as_raw_fd(),0)};assert_ne!(p as isize,-1);Self{p:p.cast(),_file:file}} fn load(&self,off:usize)->u64{unsafe{&*self.p.add(off).cast::<std::sync::atomic::AtomicU64>()}.load(std::sync::atomic::Ordering::SeqCst)}fn row(&self)->Option<[u64;16]>{for _ in 0..3{let c=self.load(64);let base=128+(c as usize&1)*128;let row=std::array::from_fn(|i|self.load(base+i*8));if c!=0&&c==self.load(64){return Some(row)}}None}}
impl Drop for Status{fn drop(&mut self){unsafe{munmap(self.p.cast(),1024);}}}
fn main(){let a:Vec<_>=env::args().collect();assert_eq!(a.len(),8);let pid:u32=a[1].parse().unwrap();let mut targets:Vec<_>=(0..2).map(|i| {let tid:u32=a[2+2*i].parse().unwrap();let start=a[3+2*i].parse().unwrap();let root=format!("/proc/{pid}/task/{tid}");let open=|name:&str|OpenOptions::new().read(true).custom_flags(0x80000).open(format!("{root}/{name}")).unwrap();Target{tid,start,stat:open("stat"),sched:open("schedstat"),wchan:open("wchan")}}).collect();let status=[Status::open(&a[6]),Status::open(&a[7])];let baseline=status.each_ref().map(|s|s.row().unwrap()[11]);let mut recent=VecDeque::with_capacity(128);let mut retained=Vec::with_capacity(192);let began=Instant::now();let start=clock(1);let cpu=clock(2);let mut trigger=0;let mut following=0;let mut count=0;let mut max_bracket=0;while began.elapsed()<Duration::from_secs(300) {let before=clock(1);let status_rows=status.each_ref().map(|s|s.row());let full=count%64==0||status_rows.iter().any(|r|r.is_some_and(|r|before.saturating_sub(r[6])>15_000_000));let threads=std::array::from_fn(|i|targets[i].sample(full));let after=clock(1);max_bracket=max_bracket.max(after-before);count+=1;let unusual=status_rows.iter().enumerate().any(|(i,r)|r.is_some_and(|r|r[11]>baseline[i]));if trigger==0&&unusual {trigger=count;retained.extend(recent.drain(..));following=64;}let row=Row{before,after,threads,status:status_rows.map(|r|r.unwrap_or([0;16]))};if following>0 {retained.push(row);following-=1;if following==0 {break}}else{if recent.len()==128 {recent.pop_front();}recent.push_back(row);}std::thread::sleep(Duration::from_millis(5));}let end=clock(1);let cpu=clock(2)-cpu;if trigger==0 {retained.extend(recent);}let stdout=std::io::stdout();let mut out=std::io::BufWriter::new(stdout.lock());writeln!(out,"{{\"clock\":\"CLOCK_MONOTONIC ns\",\"cpu_clock\":\"CLOCK_PROCESS_CPUTIME_ID ns\",\"start_ns\":{start},\"end_ns\":{end},\"cpu_ns\":{cpu},\"samples\":{count},\"trigger\":{trigger},\"max_bracket_ns\":{max_bracket},\"requested_sleep_ns\":5000000,\"capacity\":192,\"tids\":[{},{}],\"rows\":[",targets[0].tid,targets[1].tid).unwrap();for (i,r) in retained.iter().enumerate(){write!(out,"{}{{\"before_ns\":{},\"after_ns\":{},\"threads\":[",if i==0{""}else{","},r.before,r.after).unwrap();for (j,s) in r.threads.iter().enumerate(){let end=s.wchan.iter().position(|x|*x==0).unwrap_or(64);let w=std::str::from_utf8(&s.wchan[..end]).unwrap().trim();write!(out,"{}{{\"state\":\"{}\",\"minor\":{},\"major\":{},\"cpu_ns\":{},\"runnable_ns\":{},\"slices\":{},\"wchan\":\"{}\"}}",if j==0{""}else{","},s.state as char,s.minor,s.major,s.cpu,s.runqueue,s.slices,w).unwrap();}write!(out,"],\"status\":{:?}}}",r.status).unwrap();}writeln!(out,"]}}").unwrap();}
