[package]
name = "ap2-backend"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kasselvania/Linux-VST-bridge"
[features]
registered = []
[lib]
crate-type = ["staticlib"]
[dependencies]
ap1-native-client = { path = "../../native-audio-client" }
sha2 = "=0.10.9"
[profile.release]
panic = "unwind"
