"""Real Windows adapter/renderer contract checks, with only generated bytes."""
import hashlib,os,pathlib,shutil,subprocess,sys,tempfile

def run(build):
    build=pathlib.Path(build).resolve()
    with tempfile.TemporaryDirectory() as tmp:
        root=pathlib.Path(tmp);payload=root/'application.exe';shutil.copyfile(build/'naui2-application.exe',payload)
        (root/'case.txt').write_text('differential')
        for mode in ('inherited','software_rendering','--no-sandbox','inherited\nextra'):
            op=os.urandom(16).hex();token=os.urandom(32).hex();sha=hashlib.sha256(payload.read_bytes()).hexdigest()
            request=root/'request';request.write_bytes(('\n'.join(['NAUI2_LAUNCH_V1',op,token,'2',sha,str(payload.stat().st_size),str(payload),mode,''])).encode('utf-16le'))
            p=subprocess.run([str(build/'is2-launch.exe'),str(request)],cwd=root,capture_output=True,timeout=30)
            if mode in ('inherited','software_rendering'):
                assert p.returncode==0,(mode,p.returncode)
                assert p.stderr.count(b'IS2_ROOT_V1 ')==1
                assert ('IS2_ROOT_V1 '+op+' '+token+' 2 '+sha).encode() in p.stderr
                assert ('NAUI2_READY_V1 '+str(int(mode=='software_rendering'))).encode() in p.stdout
                assert (b'GPU process exited unexpectedly' in p.stderr)==(mode=='inherited')
            else:assert p.returncode!=0 and b'IS2_ROOT_V1 ' not in p.stderr
        # Child exit/cwd failure propagates through the same exact adapter.
        (root/'case.txt').unlink();request.write_bytes(('\n'.join(['NAUI2_LAUNCH_V1',op,token,'2',sha,str(payload.stat().st_size),str(payload),'inherited',''])).encode('utf-16le'))
        p=subprocess.run([str(build/'is2-launch.exe'),str(request)],cwd=root,capture_output=True,timeout=30)
        assert p.returncode==96 and b'IS2_ROOT_V1 ' in p.stderr
if __name__=='__main__':run(sys.argv[1])
