function(hp0_filter_target_link_property target_name property_name)
    if(NOT TARGET "${target_name}")
        return()
    endif()
    get_target_property(hp0_link_items "${target_name}" "${property_name}")
    if(NOT hp0_link_items OR hp0_link_items STREQUAL "hp0_link_items-NOTFOUND")
        return()
    endif()
    list(FILTER hp0_link_items EXCLUDE REGEX "^stdc\\+\\+fs$")
    set_property(TARGET "${target_name}" PROPERTY "${property_name}" "${hp0_link_items}")
endfunction()

function(hp0_remove_legacy_stdcxxfs)
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9)
        return()
    endif()

    get_property(hp0_root_targets DIRECTORY "${VST3_SDK_ROOT}" PROPERTY BUILDSYSTEM_TARGETS)
    set(hp0_targets ${hp0_root_targets} base pluginterfaces sdk_common sdk sdk_hosting
        moduleinfotool validator LabHostProbe)
    list(REMOVE_DUPLICATES hp0_targets)
    foreach(hp0_target IN LISTS hp0_targets)
        hp0_filter_target_link_property("${hp0_target}" LINK_LIBRARIES)
        hp0_filter_target_link_property("${hp0_target}" INTERFACE_LINK_LIBRARIES)
    endforeach()
endfunction()
